#Uncomment this line to define a global platform for your project
platform :ios, '7.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target ‘LiveRoomAnchorAvater’ do

pod "Masonry","1.0.1"
pod 'YYWebImage', '~> 1.0.3'
pod 'YYImage/WebP'

end
